### ISSUE TITLE
Update package on NPM 

### ISSUE THREAD

**Issue by ShivamJoker** [matmen/ImageScript#25]
Hey in npm it shows the package has not been updated since a year.

![image](https://user-images.githubusercontent.com/23727670/200360983-1cd29ba8-34f9-4642-a8aa-27f4a34c2c0d.png)

If any maintainer could push new changes with TS it would be great.

**Comment by matmen** [comment]
thanks, fixed in https://github.com/matmen/ImageScript/commit/d61031e7a8f9ea8ac6b6c9748a274c4d67ed5549
